import { LessonCategory, WordItem } from '../types';

type BaseWord = Omit<WordItem, 'imageUrl'>;

/**
 * Hand-curated vocabulary that keeps the app fully usable without network
 * access.
 */
const ALPHABET: Record<string, BaseWord[]> = {
  A: [
    { word: 'Apple', pronunciation: '/ˈæp.əl/', translation: '苹果', definition: 'A round red or green fruit.' },
    { word: 'Ant', pronunciation: '/ænt/', translation: '蚂蚁', definition: 'A tiny insect that lives in groups.' },
    { word: 'Airplane', pronunciation: '/ˈer.pleɪn/', translation: '飞机', definition: 'A machine that flies in the sky.' },
  ],
  B: [
    { word: 'Bear', pronunciation: '/ber/', translation: '熊', definition: 'A big furry animal.' },
    { word: 'Ball', pronunciation: '/bɔːl/', translation: '球', definition: 'A round toy you can throw.' },
    { word: 'Banana', pronunciation: '/bəˈnæn.ə/', translation: '香蕉', definition: 'A long yellow fruit.' },
  ],
  C: [
    { word: 'Cat', pronunciation: '/kæt/', translation: '猫', definition: 'A small furry pet.' },
    { word: 'Cow', pronunciation: '/kaʊ/', translation: '奶牛', definition: 'A big animal that gives milk.' },
    { word: 'Car', pronunciation: '/kɑːr/', translation: '汽车', definition: 'A vehicle with four wheels.' },
  ],
  D: [
    { word: 'Dog', pronunciation: '/dɔːɡ/', translation: '狗', definition: 'A friendly pet that says woof.' },
    { word: 'Duck', pronunciation: '/dʌk/', translation: '鸭子', definition: 'A bird that swims and says quack.' },
    { word: 'Drum', pronunciation: '/drʌm/', translation: '鼓', definition: 'A musical instrument you hit.' },
  ],
  E: [
    { word: 'Egg', pronunciation: '/eɡ/', translation: '鸡蛋', definition: 'A food that comes from a chicken.' },
    { word: 'Elephant', pronunciation: '/ˈel.ɪ.fənt/', translation: '大象', definition: 'A huge gray animal with a long trunk.' },
    { word: 'Ear', pronunciation: '/ɪr/', translation: '耳朵', definition: 'You use it to hear.' },
  ],
  F: [
    { word: 'Fish', pronunciation: '/fɪʃ/', translation: '鱼', definition: 'An animal that swims in water.' },
    { word: 'Frog', pronunciation: '/frɒɡ/', translation: '青蛙', definition: 'A green animal that hops.' },
    { word: 'Flower', pronunciation: '/ˈflaʊ.ər/', translation: '花', definition: 'A pretty colorful plant.' },
  ],
  G: [
    { word: 'Grape', pronunciation: '/ɡreɪp/', translation: '葡萄', definition: 'A small round juicy fruit.' },
    { word: 'Goat', pronunciation: '/ɡoʊt/', translation: '山羊', definition: 'A farm animal with horns.' },
    { word: 'Giraffe', pronunciation: '/dʒəˈræf/', translation: '长颈鹿', definition: 'A tall animal with a long neck.' },
  ],
  H: [
    { word: 'Hat', pronunciation: '/hæt/', translation: '帽子', definition: 'Something you wear on your head.' },
    { word: 'Horse', pronunciation: '/hɔːrs/', translation: '马', definition: 'A big animal you can ride.' },
    { word: 'House', pronunciation: '/haʊs/', translation: '房子', definition: 'A place where people live.' },
  ],
  I: [
    { word: 'Ice', pronunciation: '/aɪs/', translation: '冰', definition: 'Frozen water that is cold and hard.' },
    { word: 'Igloo', pronunciation: '/ˈɪɡ.luː/', translation: '冰屋', definition: 'A round house made of snow.' },
    { word: 'Insect', pronunciation: '/ˈɪn.sekt/', translation: '昆虫', definition: 'A small animal with six legs.' },
  ],
  J: [
    { word: 'Jam', pronunciation: '/dʒæm/', translation: '果酱', definition: 'Sweet fruit spread for bread.' },
    { word: 'Jet', pronunciation: '/dʒet/', translation: '喷气机', definition: 'A very fast plane.' },
    { word: 'Juice', pronunciation: '/dʒuːs/', translation: '果汁', definition: 'A sweet drink made from fruit.' },
  ],
  K: [
    { word: 'King', pronunciation: '/kɪŋ/', translation: '国王', definition: 'A man who rules a country.' },
    { word: 'Kite', pronunciation: '/kaɪt/', translation: '风筝', definition: 'A toy that flies on the wind.' },
    { word: 'Key', pronunciation: '/kiː/', translation: '钥匙', definition: 'A small metal tool that opens a lock.' },
  ],
  L: [
    { word: 'Lion', pronunciation: '/ˈlaɪ.ən/', translation: '狮子', definition: 'A big wild cat that roars.' },
    { word: 'Leaf', pronunciation: '/liːf/', translation: '叶子', definition: 'A flat green part of a tree.' },
    { word: 'Lemon', pronunciation: '/ˈlem.ən/', translation: '柠檬', definition: 'A sour yellow fruit.' },
  ],
  M: [
    { word: 'Moon', pronunciation: '/muːn/', translation: '月亮', definition: 'You can see it at night.' },
    { word: 'Milk', pronunciation: '/mɪlk/', translation: '牛奶', definition: 'A white drink from cows.' },
    { word: 'Mouse', pronunciation: '/maʊs/', translation: '老鼠', definition: 'A tiny animal with a long tail.' },
  ],
  N: [
    { word: 'Nest', pronunciation: '/nest/', translation: '鸟巢', definition: 'A home a bird builds.' },
    { word: 'Nose', pronunciation: '/noʊz/', translation: '鼻子', definition: 'You use it to smell.' },
    { word: 'Net', pronunciation: '/net/', translation: '网', definition: 'You catch fish with it.' },
  ],
  O: [
    { word: 'Orange', pronunciation: '/ˈɔːr.ɪndʒ/', translation: '橙子', definition: 'A round orange fruit.' },
    { word: 'Owl', pronunciation: '/aʊl/', translation: '猫头鹰', definition: 'A bird that hoots at night.' },
    { word: 'Octopus', pronunciation: '/ˈɑːk.tə.pəs/', translation: '章鱼', definition: 'A sea animal with eight arms.' },
  ],
  P: [
    { word: 'Pig', pronunciation: '/pɪɡ/', translation: '猪', definition: 'A pink farm animal.' },
    { word: 'Pizza', pronunciation: '/ˈpiːt.sə/', translation: '披萨', definition: 'A round food with cheese on top.' },
    { word: 'Pear', pronunciation: '/per/', translation: '梨', definition: 'A sweet green fruit.' },
  ],
  Q: [
    { word: 'Queen', pronunciation: '/kwiːn/', translation: '女王', definition: 'A woman who rules a country.' },
    { word: 'Quilt', pronunciation: '/kwɪlt/', translation: '被子', definition: 'A warm cover for your bed.' },
    { word: 'Question', pronunciation: '/ˈkwes.tʃən/', translation: '问题', definition: 'Something you ask to learn.' },
  ],
  R: [
    { word: 'Rabbit', pronunciation: '/ˈræb.ɪt/', translation: '兔子', definition: 'A small animal with long ears.' },
    { word: 'Rainbow', pronunciation: '/ˈreɪn.boʊ/', translation: '彩虹', definition: 'Colors in the sky after rain.' },
    { word: 'Robot', pronunciation: '/ˈroʊ.bɑːt/', translation: '机器人', definition: 'A machine that can move on its own.' },
  ],
  S: [
    { word: 'Sun', pronunciation: '/sʌn/', translation: '太阳', definition: 'The bright light in the daytime sky.' },
    { word: 'Star', pronunciation: '/stɑːr/', translation: '星星', definition: 'A bright light in the night sky.' },
    { word: 'Snake', pronunciation: '/sneɪk/', translation: '蛇', definition: 'A long animal with no legs.' },
  ],
  T: [
    { word: 'Tree', pronunciation: '/triː/', translation: '树', definition: 'A tall plant with leaves and branches.' },
    { word: 'Tiger', pronunciation: '/ˈtaɪ.ɡər/', translation: '老虎', definition: 'A big striped wild cat.' },
    { word: 'Train', pronunciation: '/treɪn/', translation: '火车', definition: 'A long vehicle that runs on tracks.' },
  ],
  U: [
    { word: 'Umbrella', pronunciation: '/ʌmˈbrel.ə/', translation: '雨伞', definition: 'You hold it over your head in the rain.' },
    { word: 'Unicorn', pronunciation: '/ˈjuː.nɪ.kɔːrn/', translation: '独角兽', definition: 'A make-believe horse with one horn.' },
    { word: 'Up', pronunciation: '/ʌp/', translation: '向上', definition: 'Toward a higher place.' },
  ],
  V: [
    { word: 'Van', pronunciation: '/væn/', translation: '面包车', definition: 'A big boxy car.' },
    { word: 'Vase', pronunciation: '/veɪs/', translation: '花瓶', definition: 'A jar to hold flowers.' },
    { word: 'Violin', pronunciation: '/ˌvaɪ.əˈlɪn/', translation: '小提琴', definition: 'A music instrument you play with a bow.' },
  ],
  W: [
    { word: 'Whale', pronunciation: '/weɪl/', translation: '鲸鱼', definition: 'The biggest animal in the sea.' },
    { word: 'Watermelon', pronunciation: '/ˈwɔː.tərˌmel.ən/', translation: '西瓜', definition: 'A big green fruit that is red inside.' },
    { word: 'Window', pronunciation: '/ˈwɪn.doʊ/', translation: '窗户', definition: 'A glass opening in a wall.' },
  ],
  X: [
    { word: 'Xylophone', pronunciation: '/ˈzaɪ.lə.foʊn/', translation: '木琴', definition: 'A music toy you hit with sticks.' },
    { word: 'Box', pronunciation: '/bɒks/', translation: '盒子', definition: 'A square container.' },
    { word: 'Fox', pronunciation: '/fɒks/', translation: '狐狸', definition: 'A clever orange animal.' },
  ],
  Y: [
    { word: 'Yellow', pronunciation: '/ˈjel.oʊ/', translation: '黄色', definition: 'The color of the sun.' },
    { word: 'Yo-yo', pronunciation: '/ˈjoʊ.joʊ/', translation: '溜溜球', definition: 'A round toy on a string.' },
    { word: 'Yak', pronunciation: '/jæk/', translation: '牦牛', definition: 'A big shaggy mountain animal.' },
  ],
  Z: [
    { word: 'Zebra', pronunciation: '/ˈziː.brə/', translation: '斑马', definition: 'A horse with black and white stripes.' },
    { word: 'Zoo', pronunciation: '/zuː/', translation: '动物园', definition: 'A place to see many animals.' },
    { word: 'Zero', pronunciation: '/ˈzɪr.oʊ/', translation: '零', definition: 'The number 0, meaning none.' },
  ],
};

const TOPICS: Record<string, BaseWord[]> = {
  'Farm Animals': [
    { word: 'Cow', pronunciation: '/kaʊ/', translation: '奶牛', definition: 'A big animal that gives milk.' },
    { word: 'Pig', pronunciation: '/pɪɡ/', translation: '猪', definition: 'A pink farm animal.' },
    { word: 'Sheep', pronunciation: '/ʃiːp/', translation: '羊', definition: 'A fluffy white farm animal.' },
    { word: 'Horse', pronunciation: '/hɔːrs/', translation: '马', definition: 'A big animal you can ride.' },
    { word: 'Chicken', pronunciation: '/ˈtʃɪk.ɪn/', translation: '鸡', definition: 'A bird that lays eggs.' },
    { word: 'Duck', pronunciation: '/dʌk/', translation: '鸭子', definition: 'A bird that swims and says quack.' },
    { word: 'Goat', pronunciation: '/ɡoʊt/', translation: '山羊', definition: 'A farm animal with horns.' },
    { word: 'Rabbit', pronunciation: '/ˈræb.ɪt/', translation: '兔子', definition: 'A small animal with long ears.' },
    { word: 'Donkey', pronunciation: '/ˈdɒŋ.ki/', translation: '驴', definition: 'A grey animal like a small horse.' },
    { word: 'Goose', pronunciation: '/ɡuːs/', translation: '鹅', definition: 'A big white bird with a long neck.' },
    { word: 'Turkey', pronunciation: '/ˈtɜːr.ki/', translation: '火鸡', definition: 'A large farm bird.' },
  ],
  'Fruits': [
    { word: 'Apple', pronunciation: '/ˈæp.əl/', translation: '苹果', definition: 'A round red or green fruit.' },
    { word: 'Orange', pronunciation: '/ˈɔːr.ɪndʒ/', translation: '橙子', definition: 'A round orange fruit.' },
    { word: 'Grape', pronunciation: '/ɡreɪp/', translation: '葡萄', definition: 'A small round juicy fruit.' },
    { word: 'Banana', pronunciation: '/bəˈnæn.ə/', translation: '香蕉', definition: 'A long yellow fruit.' },
    { word: 'Strawberry', pronunciation: '/ˈstrɔː.ber.i/', translation: '草莓', definition: 'A small sweet red fruit.' },
    { word: 'Watermelon', pronunciation: '/ˈwɔː.tərˌmel.ən/', translation: '西瓜', definition: 'A big green fruit that is red inside.' },
    { word: 'Pear', pronunciation: '/per/', translation: '梨', definition: 'A sweet green fruit.' },
    { word: 'Peach', pronunciation: '/piːtʃ/', translation: '桃子', definition: 'A soft pink-orange fruit.' },
    { word: 'Lemon', pronunciation: '/ˈlem.ən/', translation: '柠檬', definition: 'A sour yellow fruit.' },
    { word: 'Cherry', pronunciation: '/ˈtʃer.i/', translation: '樱桃', definition: 'A tiny red fruit with a stem.' },
    { word: 'Pineapple', pronunciation: '/ˈpaɪnˌæp.əl/', translation: '菠萝', definition: 'A spiky tropical fruit.' },
  ],
  'Family': [
    { word: 'Mom', pronunciation: '/mɑːm/', translation: '妈妈', definition: 'Your female parent.' },
    { word: 'Dad', pronunciation: '/dæd/', translation: '爸爸', definition: 'Your male parent.' },
    { word: 'Baby', pronunciation: '/ˈbeɪ.bi/', translation: '宝宝', definition: 'A very young child.' },
    { word: 'Sister', pronunciation: '/ˈsɪs.tər/', translation: '姐妹', definition: 'A girl in your family.' },
    { word: 'Brother', pronunciation: '/ˈbrʌð.ər/', translation: '兄弟', definition: 'A boy in your family.' },
    { word: 'Grandma', pronunciation: '/ˈɡræn.mɑː/', translation: '奶奶', definition: 'Your mom\'s or dad\'s mom.' },
    { word: 'Grandpa', pronunciation: '/ˈɡræn.pɑː/', translation: '爷爷', definition: 'Your mom\'s or dad\'s dad.' },
    { word: 'Aunt', pronunciation: '/ænt/', translation: '阿姨', definition: 'Your mom\'s or dad\'s sister.' },
    { word: 'Uncle', pronunciation: '/ˈʌŋ.kəl/', translation: '叔叔', definition: 'Your mom\'s or dad\'s brother.' },
    { word: 'Cousin', pronunciation: '/ˈkʌz.ən/', translation: '表兄弟姐妹', definition: 'Your aunt or uncle\'s child.' },
    { word: 'Family', pronunciation: '/ˈfæm.əl.i/', translation: '家庭', definition: 'The people you live with and love.' },
  ],
  'Colors': [
    { word: 'Red', pronunciation: '/red/', translation: '红色', definition: 'The color of strawberries.' },
    { word: 'Blue', pronunciation: '/bluː/', translation: '蓝色', definition: 'The color of the sky.' },
    { word: 'Green', pronunciation: '/ɡriːn/', translation: '绿色', definition: 'The color of grass.' },
    { word: 'Yellow', pronunciation: '/ˈjel.oʊ/', translation: '黄色', definition: 'The color of the sun.' },
    { word: 'Orange', pronunciation: '/ˈɔːr.ɪndʒ/', translation: '橙色', definition: 'The color of a carrot.' },
    { word: 'Purple', pronunciation: '/ˈpɜːr.pəl/', translation: '紫色', definition: 'The color of grapes.' },
    { word: 'Pink', pronunciation: '/pɪŋk/', translation: '粉色', definition: 'A soft, light red color.' },
    { word: 'Black', pronunciation: '/blæk/', translation: '黑色', definition: 'The color of the night.' },
    { word: 'White', pronunciation: '/waɪt/', translation: '白色', definition: 'The color of snow.' },
    { word: 'Brown', pronunciation: '/braʊn/', translation: '棕色', definition: 'The color of chocolate.' },
    { word: 'Gray', pronunciation: '/ɡreɪ/', translation: '灰色', definition: 'The color of clouds before rain.' },
  ],
  'Vehicles': [
    { word: 'Car', pronunciation: '/kɑːr/', translation: '汽车', definition: 'A vehicle with four wheels.' },
    { word: 'Bus', pronunciation: '/bʌs/', translation: '公共汽车', definition: 'A long vehicle that carries many people.' },
    { word: 'Train', pronunciation: '/treɪn/', translation: '火车', definition: 'A long vehicle that runs on tracks.' },
    { word: 'Plane', pronunciation: '/pleɪn/', translation: '飞机', definition: 'A machine that flies in the sky.' },
    { word: 'Boat', pronunciation: '/boʊt/', translation: '船', definition: 'A vehicle that goes on water.' },
    { word: 'Bike', pronunciation: '/baɪk/', translation: '自行车', definition: 'A vehicle with two wheels you pedal.' },
    { word: 'Truck', pronunciation: '/trʌk/', translation: '卡车', definition: 'A big vehicle that carries heavy things.' },
    { word: 'Ship', pronunciation: '/ʃɪp/', translation: '轮船', definition: 'A very big boat.' },
    { word: 'Helicopter', pronunciation: '/ˈhel.ɪˌkɑːp.tər/', translation: '直升机', definition: 'A flying machine with spinning blades.' },
    { word: 'Taxi', pronunciation: '/ˈtæk.si/', translation: '出租车', definition: 'A car you pay to ride in.' },
    { word: 'Scooter', pronunciation: '/ˈskuː.tər/', translation: '滑板车', definition: 'A small vehicle you push with your foot.' },
  ],
  'Body Parts': [
    { word: 'Eye', pronunciation: '/aɪ/', translation: '眼睛', definition: 'You use it to see.' },
    { word: 'Ear', pronunciation: '/ɪr/', translation: '耳朵', definition: 'You use it to hear.' },
    { word: 'Nose', pronunciation: '/noʊz/', translation: '鼻子', definition: 'You use it to smell.' },
    { word: 'Mouth', pronunciation: '/maʊθ/', translation: '嘴巴', definition: 'You use it to eat and talk.' },
    { word: 'Hand', pronunciation: '/hænd/', translation: '手', definition: 'You use it to hold things.' },
    { word: 'Foot', pronunciation: '/fʊt/', translation: '脚', definition: 'You stand and walk on it.' },
    { word: 'Head', pronunciation: '/hed/', translation: '头', definition: 'The top part of your body.' },
    { word: 'Hair', pronunciation: '/her/', translation: '头发', definition: 'It grows on top of your head.' },
    { word: 'Arm', pronunciation: '/ɑːrm/', translation: '手臂', definition: 'It connects your hand to your body.' },
    { word: 'Leg', pronunciation: '/leɡ/', translation: '腿', definition: 'You use it to walk and run.' },
    { word: 'Tooth', pronunciation: '/tuːθ/', translation: '牙齿', definition: 'It helps you chew food.' },
  ],
  'Clothing': [
    { word: 'Shirt', pronunciation: '/ʃɜːrt/', translation: '衬衫', definition: 'You wear it on your top.' },
    { word: 'Pants', pronunciation: '/pænts/', translation: '裤子', definition: 'You wear them on your legs.' },
    { word: 'Shoes', pronunciation: '/ʃuːz/', translation: '鞋子', definition: 'You wear them on your feet.' },
    { word: 'Hat', pronunciation: '/hæt/', translation: '帽子', definition: 'You wear it on your head.' },
    { word: 'Socks', pronunciation: '/sɑːks/', translation: '袜子', definition: 'You wear them inside your shoes.' },
    { word: 'Dress', pronunciation: '/dres/', translation: '连衣裙', definition: 'A piece of clothing for girls.' },
    { word: 'Coat', pronunciation: '/koʊt/', translation: '外套', definition: 'You wear it when it is cold.' },
    { word: 'Skirt', pronunciation: '/skɜːrt/', translation: '裙子', definition: 'A piece of clothing that hangs from the waist.' },
    { word: 'Gloves', pronunciation: '/ɡlʌvz/', translation: '手套', definition: 'You wear them on your hands.' },
    { word: 'Scarf', pronunciation: '/skɑːrf/', translation: '围巾', definition: 'You wear it around your neck.' },
    { word: 'Boots', pronunciation: '/buːts/', translation: '靴子', definition: 'Tall shoes for rain or snow.' },
  ],
  'School': [
    { word: 'Book', pronunciation: '/bʊk/', translation: '书', definition: 'You read it to learn things.' },
    { word: 'Pen', pronunciation: '/pen/', translation: '钢笔', definition: 'You use it to write.' },
    { word: 'Pencil', pronunciation: '/ˈpen.səl/', translation: '铅笔', definition: 'A wooden stick to draw or write.' },
    { word: 'Desk', pronunciation: '/desk/', translation: '书桌', definition: 'A table where you study.' },
    { word: 'Chair', pronunciation: '/tʃer/', translation: '椅子', definition: 'You sit on it.' },
    { word: 'Bag', pronunciation: '/bæɡ/', translation: '书包', definition: 'You carry your books in it.' },
    { word: 'Teacher', pronunciation: '/ˈtiː.tʃər/', translation: '老师', definition: 'A person who helps you learn.' },
    { word: 'Eraser', pronunciation: '/ɪˈreɪ.sər/', translation: '橡皮', definition: 'You use it to remove pencil marks.' },
    { word: 'Ruler', pronunciation: '/ˈruː.lər/', translation: '尺子', definition: 'You use it to measure or draw lines.' },
    { word: 'Crayon', pronunciation: '/ˈkreɪ.ɑːn/', translation: '蜡笔', definition: 'A colored stick to draw with.' },
    { word: 'Scissors', pronunciation: '/ˈsɪz.ərz/', translation: '剪刀', definition: 'You use them to cut paper.' },
  ],
  'Nature': [
    { word: 'Tree', pronunciation: '/triː/', translation: '树', definition: 'A tall plant with leaves and branches.' },
    { word: 'Flower', pronunciation: '/ˈflaʊ.ər/', translation: '花', definition: 'A pretty colorful plant.' },
    { word: 'Grass', pronunciation: '/ɡræs/', translation: '草', definition: 'Green plants that cover the ground.' },
    { word: 'River', pronunciation: '/ˈrɪv.ər/', translation: '河', definition: 'Water that flows across the land.' },
    { word: 'Mountain', pronunciation: '/ˈmaʊn.tən/', translation: '山', definition: 'A very tall, rocky hill.' },
    { word: 'Rock', pronunciation: '/rɑːk/', translation: '石头', definition: 'A hard piece of stone.' },
    { word: 'Leaf', pronunciation: '/liːf/', translation: '叶子', definition: 'A flat green part of a tree.' },
    { word: 'Hill', pronunciation: '/hɪl/', translation: '小山', definition: 'A small mountain.' },
    { word: 'Lake', pronunciation: '/leɪk/', translation: '湖', definition: 'A big pool of water.' },
    { word: 'Forest', pronunciation: '/ˈfɔːr.ɪst/', translation: '森林', definition: 'A place with many trees.' },
    { word: 'Bush', pronunciation: '/bʊʃ/', translation: '灌木', definition: 'A small low plant with many branches.' },
  ],
  'Yummy Food': [
    { word: 'Pizza', pronunciation: '/ˈpiːt.sə/', translation: '披萨', definition: 'A round food with cheese on top.' },
    { word: 'Bread', pronunciation: '/bred/', translation: '面包', definition: 'A soft food made from flour.' },
    { word: 'Cake', pronunciation: '/keɪk/', translation: '蛋糕', definition: 'A sweet treat for birthdays.' },
    { word: 'Rice', pronunciation: '/raɪs/', translation: '米饭', definition: 'Tiny white grains you eat.' },
    { word: 'Egg', pronunciation: '/eɡ/', translation: '鸡蛋', definition: 'A food that comes from a chicken.' },
    { word: 'Milk', pronunciation: '/mɪlk/', translation: '牛奶', definition: 'A white drink from cows.' },
    { word: 'Cheese', pronunciation: '/tʃiːz/', translation: '奶酪', definition: 'A yellow food made from milk.' },
    { word: 'Cookie', pronunciation: '/ˈkʊk.i/', translation: '饼干', definition: 'A sweet, crunchy snack.' },
    { word: 'Soup', pronunciation: '/suːp/', translation: '汤', definition: 'A warm liquid food in a bowl.' },
    { word: 'Noodles', pronunciation: '/ˈnuː.dəlz/', translation: '面条', definition: 'Long thin strings of food.' },
    { word: 'Sandwich', pronunciation: '/ˈsæn.wɪtʃ/', translation: '三明治', definition: 'Food between two slices of bread.' },
  ],
  'Space': [
    { word: 'Star', pronunciation: '/stɑːr/', translation: '星星', definition: 'A bright light in the night sky.' },
    { word: 'Sun', pronunciation: '/sʌn/', translation: '太阳', definition: 'The bright light in the daytime sky.' },
    { word: 'Moon', pronunciation: '/muːn/', translation: '月亮', definition: 'You can see it at night.' },
    { word: 'Earth', pronunciation: '/ɜːrθ/', translation: '地球', definition: 'The planet where we live.' },
    { word: 'Planet', pronunciation: '/ˈplæn.ɪt/', translation: '行星', definition: 'A big round ball in space.' },
    { word: 'Rocket', pronunciation: '/ˈrɑː.kɪt/', translation: '火箭', definition: 'A vehicle that flies into space.' },
    { word: 'Astronaut', pronunciation: '/ˈæs.trə.nɑːt/', translation: '宇航员', definition: 'A person who travels in space.' },
    { word: 'Comet', pronunciation: '/ˈkɑː.mɪt/', translation: '彗星', definition: 'A space ball with a long tail.' },
    { word: 'Galaxy', pronunciation: '/ˈɡæl.ək.si/', translation: '星系', definition: 'A huge group of stars.' },
    { word: 'Alien', pronunciation: '/ˈeɪ.li.ən/', translation: '外星人', definition: 'A make-believe creature from space.' },
    { word: 'Satellite', pronunciation: '/ˈsæt.əl.aɪt/', translation: '卫星', definition: 'A machine that goes around a planet.' },
  ],
  'Ocean Life': [
    { word: 'Fish', pronunciation: '/fɪʃ/', translation: '鱼', definition: 'An animal that swims in water.' },
    { word: 'Shark', pronunciation: '/ʃɑːrk/', translation: '鲨鱼', definition: 'A big fish with sharp teeth.' },
    { word: 'Whale', pronunciation: '/weɪl/', translation: '鲸鱼', definition: 'The biggest animal in the sea.' },
    { word: 'Dolphin', pronunciation: '/ˈdɑːl.fɪn/', translation: '海豚', definition: 'A smart, friendly sea animal.' },
    { word: 'Octopus', pronunciation: '/ˈɑːk.tə.pəs/', translation: '章鱼', definition: 'A sea animal with eight arms.' },
    { word: 'Crab', pronunciation: '/kræb/', translation: '螃蟹', definition: 'A sea animal that walks sideways.' },
    { word: 'Turtle', pronunciation: '/ˈtɜːr.təl/', translation: '海龟', definition: 'A sea animal with a hard shell.' },
    { word: 'Seahorse', pronunciation: '/ˈsiː.hɔːrs/', translation: '海马', definition: 'A tiny sea animal shaped like a horse.' },
    { word: 'Starfish', pronunciation: '/ˈstɑːr.fɪʃ/', translation: '海星', definition: 'A sea animal shaped like a star.' },
    { word: 'Jellyfish', pronunciation: '/ˈdʒel.iˌfɪʃ/', translation: '水母', definition: 'A soft, see-through sea animal.' },
    { word: 'Seal', pronunciation: '/siːl/', translation: '海豹', definition: 'A sea animal that claps and barks.' },
  ],
  'Numbers 1-10': [
    { word: 'One', pronunciation: '/wʌn/', translation: '一', definition: 'The number 1.' },
    { word: 'Two', pronunciation: '/tuː/', translation: '二', definition: 'The number 2.' },
    { word: 'Three', pronunciation: '/θriː/', translation: '三', definition: 'The number 3.' },
    { word: 'Four', pronunciation: '/fɔːr/', translation: '四', definition: 'The number 4.' },
    { word: 'Five', pronunciation: '/faɪv/', translation: '五', definition: 'The number 5.' },
    { word: 'Six', pronunciation: '/sɪks/', translation: '六', definition: 'The number 6.' },
    { word: 'Seven', pronunciation: '/ˈsev.ən/', translation: '七', definition: 'The number 7.' },
    { word: 'Eight', pronunciation: '/eɪt/', translation: '八', definition: 'The number 8.' },
    { word: 'Nine', pronunciation: '/naɪn/', translation: '九', definition: 'The number 9.' },
    { word: 'Ten', pronunciation: '/ten/', translation: '十', definition: 'The number 10.' },
  ],
  'Shapes': [
    { word: 'Circle', pronunciation: '/ˈsɜːr.kəl/', translation: '圆形', definition: 'A round shape, like a wheel.' },
    { word: 'Square', pronunciation: '/skwer/', translation: '正方形', definition: 'A shape with four equal sides.' },
    { word: 'Triangle', pronunciation: '/ˈtraɪ.æŋ.ɡəl/', translation: '三角形', definition: 'A shape with three sides.' },
    { word: 'Rectangle', pronunciation: '/ˈrek.tæŋ.ɡəl/', translation: '长方形', definition: 'A shape like a long box.' },
    { word: 'Star', pronunciation: '/stɑːr/', translation: '星形', definition: 'A shape with pointy tips.' },
    { word: 'Heart', pronunciation: '/hɑːrt/', translation: '心形', definition: 'The shape you give for love.' },
    { word: 'Oval', pronunciation: '/ˈoʊ.vəl/', translation: '椭圆形', definition: 'A shape like a stretched circle.' },
    { word: 'Diamond', pronunciation: '/ˈdaɪ.mənd/', translation: '菱形', definition: 'A shape like a tilted square.' },
    { word: 'Crescent', pronunciation: '/ˈkres.ənt/', translation: '月牙形', definition: 'A curved shape like a new moon.' },
    { word: 'Pentagon', pronunciation: '/ˈpen.tə.ɡɑːn/', translation: '五边形', definition: 'A shape with five sides.' },
    { word: 'Hexagon', pronunciation: '/ˈhek.sə.ɡɑːn/', translation: '六边形', definition: 'A shape with six sides, like a honeycomb cell.' },
  ],
  'Weather': [
    { word: 'Sun', pronunciation: '/sʌn/', translation: '太阳', definition: 'It makes the day warm and bright.' },
    { word: 'Rain', pronunciation: '/reɪn/', translation: '雨', definition: 'Water falling from the sky.' },
    { word: 'Snow', pronunciation: '/snoʊ/', translation: '雪', definition: 'White fluffy flakes from the sky.' },
    { word: 'Cloud', pronunciation: '/klaʊd/', translation: '云', definition: 'A fluffy white shape in the sky.' },
    { word: 'Wind', pronunciation: '/wɪnd/', translation: '风', definition: 'Air that blows around you.' },
    { word: 'Storm', pronunciation: '/stɔːrm/', translation: '暴风雨', definition: 'Strong wind and heavy rain.' },
    { word: 'Rainbow', pronunciation: '/ˈreɪn.boʊ/', translation: '彩虹', definition: 'Colors in the sky after rain.' },
    { word: 'Lightning', pronunciation: '/ˈlaɪt.nɪŋ/', translation: '闪电', definition: 'A bright flash in a storm.' },
    { word: 'Thunder', pronunciation: '/ˈθʌn.dər/', translation: '雷', definition: 'A loud boom from the sky.' },
    { word: 'Fog', pronunciation: '/fɑːɡ/', translation: '雾', definition: 'A thick cloud near the ground.' },
    { word: 'Ice', pronunciation: '/aɪs/', translation: '冰', definition: 'Frozen water that is cold and hard.' },
  ],
  'Toys': [
    { word: 'Ball', pronunciation: '/bɔːl/', translation: '球', definition: 'A round toy you can throw.' },
    { word: 'Doll', pronunciation: '/dɑːl/', translation: '娃娃', definition: 'A toy that looks like a person.' },
    { word: 'Teddy', pronunciation: '/ˈted.i/', translation: '玩具熊', definition: 'A soft cuddly toy bear.' },
    { word: 'Blocks', pronunciation: '/blɑːks/', translation: '积木', definition: 'Small bricks you stack up.' },
    { word: 'Puzzle', pronunciation: '/ˈpʌz.əl/', translation: '拼图', definition: 'Pieces you put together to make a picture.' },
    { word: 'Yo-yo', pronunciation: '/ˈjoʊ.joʊ/', translation: '溜溜球', definition: 'A round toy that goes up and down on a string.' },
    { word: 'Kite', pronunciation: '/kaɪt/', translation: '风筝', definition: 'A toy that flies on the wind.' },
    { word: 'Drum', pronunciation: '/drʌm/', translation: '鼓', definition: 'A toy that makes loud beats.' },
    { word: 'Top', pronunciation: '/tɒp/', translation: '陀螺', definition: 'A toy that spins around.' },
    { word: 'Robot', pronunciation: '/ˈroʊ.bɑːt/', translation: '机器人', definition: 'A toy that moves like a machine.' },
    { word: 'Balloon', pronunciation: '/bəˈluːn/', translation: '气球', definition: 'A toy you blow up with air.' },
  ],
};

const PHONETICS: Record<string, BaseWord[]> = {
  'Short A /æ/': [
    { word: 'Cat', pronunciation: '/kæt/', translation: '猫', definition: 'A small furry pet.' },
    { word: 'Hat', pronunciation: '/hæt/', translation: '帽子', definition: 'Something you wear on your head.' },
    { word: 'Bag', pronunciation: '/bæɡ/', translation: '包', definition: 'You carry things in it.' },
    { word: 'Map', pronunciation: '/mæp/', translation: '地图', definition: 'A picture that shows places.' },
    { word: 'Apple', pronunciation: '/ˈæp.əl/', translation: '苹果', definition: 'A round red or green fruit.' },
    { word: 'Fan', pronunciation: '/fæn/', translation: '风扇', definition: 'It moves air to cool you.' },
    { word: 'Pan', pronunciation: '/pæn/', translation: '平底锅', definition: 'You cook food in it.' },
    { word: 'Ant', pronunciation: '/ænt/', translation: '蚂蚁', definition: 'A tiny insect on the ground.' },
    { word: 'Van', pronunciation: '/væn/', translation: '面包车', definition: 'A big boxy car.' },
    { word: 'Rabbit', pronunciation: '/ˈræb.ɪt/', translation: '兔子', definition: 'A small animal with long ears.' },
    { word: 'Jam', pronunciation: '/dʒæm/', translation: '果酱', definition: 'Sweet fruit spread for bread.' },
  ],
  'Short E /e/': [
    { word: 'Bed', pronunciation: '/bed/', translation: '床', definition: 'You sleep on it at night.' },
    { word: 'Red', pronunciation: '/red/', translation: '红色', definition: 'The color of strawberries.' },
    { word: 'Egg', pronunciation: '/eɡ/', translation: '鸡蛋', definition: 'A food that comes from a chicken.' },
    { word: 'Pen', pronunciation: '/pen/', translation: '钢笔', definition: 'You use it to write.' },
    { word: 'Hen', pronunciation: '/hen/', translation: '母鸡', definition: 'A female chicken that lays eggs.' },
    { word: 'Net', pronunciation: '/net/', translation: '网', definition: 'You catch fish with it.' },
    { word: 'Web', pronunciation: '/web/', translation: '网', definition: 'A spider makes one to catch bugs.' },
    { word: 'Jet', pronunciation: '/dʒet/', translation: '喷气机', definition: 'A very fast plane.' },
    { word: 'Tent', pronunciation: '/tent/', translation: '帐篷', definition: 'A cloth house for camping.' },
    { word: 'Bell', pronunciation: '/bel/', translation: '铃铛', definition: 'It makes a ringing sound.' },
    { word: 'Nest', pronunciation: '/nest/', translation: '鸟巢', definition: 'A home a bird builds.' },
  ],
  'Short I /ɪ/': [
    { word: 'Pig', pronunciation: '/pɪɡ/', translation: '猪', definition: 'A pink farm animal.' },
    { word: 'Sit', pronunciation: '/sɪt/', translation: '坐', definition: 'To rest on a chair.' },
    { word: 'Big', pronunciation: '/bɪɡ/', translation: '大的', definition: 'Not small.' },
    { word: 'Fish', pronunciation: '/fɪʃ/', translation: '鱼', definition: 'An animal that swims in water.' },
    { word: 'Pin', pronunciation: '/pɪn/', translation: '别针', definition: 'A small sharp metal stick.' },
    { word: 'Lip', pronunciation: '/lɪp/', translation: '嘴唇', definition: 'The edge of your mouth.' },
    { word: 'Six', pronunciation: '/sɪks/', translation: '六', definition: 'The number 6.' },
    { word: 'Hill', pronunciation: '/hɪl/', translation: '小山', definition: 'A small mountain.' },
    { word: 'Milk', pronunciation: '/mɪlk/', translation: '牛奶', definition: 'A white drink from cows.' },
    { word: 'Ship', pronunciation: '/ʃɪp/', translation: '轮船', definition: 'A very big boat.' },
    { word: 'King', pronunciation: '/kɪŋ/', translation: '国王', definition: 'A man who rules a country.' },
  ],
  'Short O /ɒ/': [
    { word: 'Dog', pronunciation: '/dɒɡ/', translation: '狗', definition: 'A pet that says woof.' },
    { word: 'Fox', pronunciation: '/fɒks/', translation: '狐狸', definition: 'A clever orange animal.' },
    { word: 'Box', pronunciation: '/bɒks/', translation: '盒子', definition: 'A square container.' },
    { word: 'Hot', pronunciation: '/hɒt/', translation: '热的', definition: 'Very warm, not cold.' },
    { word: 'Pot', pronunciation: '/pɒt/', translation: '锅', definition: 'You cook soup in it.' },
    { word: 'Mop', pronunciation: '/mɒp/', translation: '拖把', definition: 'You clean the floor with it.' },
    { word: 'Top', pronunciation: '/tɒp/', translation: '陀螺', definition: 'A toy that spins around.' },
    { word: 'Frog', pronunciation: '/frɒɡ/', translation: '青蛙', definition: 'A green animal that hops.' },
    { word: 'Sock', pronunciation: '/sɒk/', translation: '袜子', definition: 'You wear it on your foot.' },
    { word: 'Clock', pronunciation: '/klɒk/', translation: '钟', definition: 'It tells you the time.' },
    { word: 'Rock', pronunciation: '/rɒk/', translation: '石头', definition: 'A hard piece of stone.' },
  ],
  'Short U /ʌ/': [
    { word: 'Bus', pronunciation: '/bʌs/', translation: '公共汽车', definition: 'A long vehicle for many people.' },
    { word: 'Cup', pronunciation: '/kʌp/', translation: '杯子', definition: 'You drink water from it.' },
    { word: 'Sun', pronunciation: '/sʌn/', translation: '太阳', definition: 'The bright light in the daytime sky.' },
    { word: 'Bug', pronunciation: '/bʌɡ/', translation: '虫子', definition: 'A small insect.' },
    { word: 'Mug', pronunciation: '/mʌɡ/', translation: '马克杯', definition: 'A big cup with a handle.' },
    { word: 'Run', pronunciation: '/rʌn/', translation: '跑', definition: 'To move fast on your feet.' },
    { word: 'Duck', pronunciation: '/dʌk/', translation: '鸭子', definition: 'A bird that says quack.' },
    { word: 'Drum', pronunciation: '/drʌm/', translation: '鼓', definition: 'A toy that makes loud beats.' },
    { word: 'Nut', pronunciation: '/nʌt/', translation: '坚果', definition: 'A small hard food in a shell.' },
    { word: 'Jump', pronunciation: '/dʒʌmp/', translation: '跳', definition: 'To push up off the ground.' },
    { word: 'Hug', pronunciation: '/hʌɡ/', translation: '拥抱', definition: 'To hold someone with love.' },
  ],
  'Sound /s/': [
    { word: 'Sun', pronunciation: '/sʌn/', translation: '太阳', definition: 'The bright light in the daytime sky.' },
    { word: 'Snake', pronunciation: '/sneɪk/', translation: '蛇', definition: 'A long animal with no legs.' },
    { word: 'Sock', pronunciation: '/sɑːk/', translation: '袜子', definition: 'You wear it on your foot.' },
    { word: 'Sand', pronunciation: '/sænd/', translation: '沙子', definition: 'Tiny rocks on the beach.' },
    { word: 'Soup', pronunciation: '/suːp/', translation: '汤', definition: 'A warm liquid food in a bowl.' },
    { word: 'Seed', pronunciation: '/siːd/', translation: '种子', definition: 'A tiny thing that grows into a plant.' },
    { word: 'Sing', pronunciation: '/sɪŋ/', translation: '唱歌', definition: 'To make music with your voice.' },
    { word: 'Star', pronunciation: '/stɑːr/', translation: '星星', definition: 'A bright light in the night sky.' },
    { word: 'Soap', pronunciation: '/soʊp/', translation: '肥皂', definition: 'You use it to wash hands.' },
    { word: 'Smile', pronunciation: '/smaɪl/', translation: '微笑', definition: 'A happy look on your face.' },
    { word: 'Sit', pronunciation: '/sɪt/', translation: '坐', definition: 'To rest on a chair.' },
  ],
  'Sound /sh/': [
    { word: 'Ship', pronunciation: '/ʃɪp/', translation: '轮船', definition: 'A very big boat.' },
    { word: 'Shoe', pronunciation: '/ʃuː/', translation: '鞋', definition: 'You wear it on your foot.' },
    { word: 'Shell', pronunciation: '/ʃel/', translation: '贝壳', definition: 'A hard cover from a sea animal.' },
    { word: 'Shark', pronunciation: '/ʃɑːrk/', translation: '鲨鱼', definition: 'A big fish with sharp teeth.' },
    { word: 'Sheep', pronunciation: '/ʃiːp/', translation: '羊', definition: 'A fluffy white farm animal.' },
    { word: 'Fish', pronunciation: '/fɪʃ/', translation: '鱼', definition: 'An animal that swims in water.' },
    { word: 'Brush', pronunciation: '/brʌʃ/', translation: '刷子', definition: 'You use it to clean teeth or hair.' },
    { word: 'Dish', pronunciation: '/dɪʃ/', translation: '盘子', definition: 'A plate you put food on.' },
    { word: 'Shop', pronunciation: '/ʃɑːp/', translation: '商店', definition: 'A place where you buy things.' },
    { word: 'Wash', pronunciation: '/wɑːʃ/', translation: '洗', definition: 'To clean with water.' },
    { word: 'Shower', pronunciation: '/ˈʃaʊ.ər/', translation: '淋浴', definition: 'You wash under it.' },
  ],
  'Sound /ch/': [
    { word: 'Cheese', pronunciation: '/tʃiːz/', translation: '奶酪', definition: 'A yellow food made from milk.' },
    { word: 'Chair', pronunciation: '/tʃer/', translation: '椅子', definition: 'You sit on it.' },
    { word: 'Cherry', pronunciation: '/ˈtʃer.i/', translation: '樱桃', definition: 'A tiny red fruit with a stem.' },
    { word: 'Chick', pronunciation: '/tʃɪk/', translation: '小鸡', definition: 'A baby chicken.' },
    { word: 'Chin', pronunciation: '/tʃɪn/', translation: '下巴', definition: 'The part of your face below your mouth.' },
    { word: 'Cheek', pronunciation: '/tʃiːk/', translation: '脸颊', definition: 'The soft part on the side of your face.' },
    { word: 'Lunch', pronunciation: '/lʌntʃ/', translation: '午餐', definition: 'The meal you eat at noon.' },
    { word: 'Beach', pronunciation: '/biːtʃ/', translation: '沙滩', definition: 'A sandy place by the sea.' },
    { word: 'Peach', pronunciation: '/piːtʃ/', translation: '桃子', definition: 'A soft pink-orange fruit.' },
    { word: 'Chocolate', pronunciation: '/ˈtʃɑːk.lət/', translation: '巧克力', definition: 'A sweet brown treat.' },
    { word: 'Chip', pronunciation: '/tʃɪp/', translation: '薯片', definition: 'A thin crunchy snack.' },
  ],
  'Sound /th/': [
    { word: 'Thumb', pronunciation: '/θʌm/', translation: '拇指', definition: 'The short fat finger on your hand.' },
    { word: 'Three', pronunciation: '/θriː/', translation: '三', definition: 'The number 3.' },
    { word: 'Thin', pronunciation: '/θɪn/', translation: '瘦的', definition: 'Not fat or thick.' },
    { word: 'Thick', pronunciation: '/θɪk/', translation: '厚的', definition: 'Wide from one side to the other.' },
    { word: 'Bath', pronunciation: '/bæθ/', translation: '洗澡', definition: 'You wash your body in it.' },
    { word: 'Math', pronunciation: '/mæθ/', translation: '数学', definition: 'Working with numbers.' },
    { word: 'Tooth', pronunciation: '/tuːθ/', translation: '牙齿', definition: 'It helps you chew food.' },
    { word: 'Mouth', pronunciation: '/maʊθ/', translation: '嘴巴', definition: 'You use it to eat and talk.' },
    { word: 'Path', pronunciation: '/pæθ/', translation: '小路', definition: 'A small road for walking.' },
    { word: 'Throne', pronunciation: '/θroʊn/', translation: '王座', definition: 'A fancy chair for a king.' },
    { word: 'Thorn', pronunciation: '/θɔːrn/', translation: '刺', definition: 'A sharp point on a plant.' },
  ],
};

const GENERIC: BaseWord[] = [
  { word: 'Star', pronunciation: '/stɑːr/', translation: '星星', definition: 'A bright light in the night sky.' },
  { word: 'Sun', pronunciation: '/sʌn/', translation: '太阳', definition: 'The bright light in the daytime sky.' },
  { word: 'Moon', pronunciation: '/muːn/', translation: '月亮', definition: 'You can see it at night.' },
  { word: 'Tree', pronunciation: '/triː/', translation: '树', definition: 'A tall plant with leaves and branches.' },
  { word: 'Flower', pronunciation: '/ˈflaʊ.ər/', translation: '花', definition: 'A pretty colorful plant.' },
  { word: 'Bird', pronunciation: '/bɜːrd/', translation: '鸟', definition: 'A small animal that can fly.' },
  { word: 'Fish', pronunciation: '/fɪʃ/', translation: '鱼', definition: 'An animal that swims in water.' },
  { word: 'House', pronunciation: '/haʊs/', translation: '房子', definition: 'A place where people live.' },
  { word: 'Cloud', pronunciation: '/klaʊd/', translation: '云', definition: 'A fluffy white shape in the sky.' },
  { word: 'Rainbow', pronunciation: '/ˈreɪn.boʊ/', translation: '彩虹', definition: 'Colors in the sky after rain.' },
  { word: 'Smile', pronunciation: '/smaɪl/', translation: '微笑', definition: 'A happy look on your face.' },
];

export function getFallbackVocabulary(topic: string, category: LessonCategory): BaseWord[] {
  if (category === 'alphabet') {
    const letter = topic.replace(/^Letter\s+/i, '').trim().toUpperCase();
    if (ALPHABET[letter]) return ALPHABET[letter];
    // Unknown letter: fall back to a small set of generic words instead of
    // synthesizing fake non-existent words.
    return GENERIC.slice(0, 3);
  }
  if (category === 'phonetics') {
    return PHONETICS[topic] ?? GENERIC;
  }
  return TOPICS[topic] ?? GENERIC;
}

/** A tiny 1x1 transparent PNG, used as an inert placeholder when image gen is unavailable. */
export const PLACEHOLDER_IMAGE =
  'data:image/svg+xml;utf8,' +
  encodeURIComponent(
    `<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 200 200'>
      <rect width='200' height='200' fill='#FFE7B3'/>
      <text x='50%' y='54%' font-size='90' text-anchor='middle' font-family='Comic Sans MS, sans-serif'>🎨</text>
    </svg>`,
  );
